"use client";
import React from "react";
import Head from "next/head";
import Link from "next/link";
import { addCampaign, getLastCampaignId } from "../../services/Web3Service";
import { useState } from "react";
import {
  Container,
  FormDiv,
  Form,
  InputDiv,
  MessageDiv,
  BtnReturn,
} from "../../css/campaignStyles";
import GlobalStyles from "../../../GlobalStyles";

const Campaign = () => {
  const [campaign, setCampain] = useState({});
  const [message, setMessage] = useState("");

  function onInputChange(evt) {
    setCampain((prevState) => ({
      ...prevState,
      [evt.target.id]: evt.target.value,
    }));
  }

  function btnSaveClick() {
    setMessage("Saving please wait......");
    addCampaign(campaign)
      .then((tx) => getLastCampaignId())
      .then((id) =>
        setMessage(
          `Campaign saved with ID ${id}. Tell your friends and pass this number on to them.`
        )
      )
      .catch((err) => {
        console.error(err);
        setMessage(err.message);
      });
  }
  return (
    <>
      <GlobalStyles />
      <Head>
        <title>Donate Crypto</title>
        <meta charSet="UTF-8" />
        <meta name="description" content="Generated by Next.js" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Container>
        <FormDiv>
          <h1>Create Your Campaign</h1>
          <Form>
            <input
              type="text"
              id="title"
              name="title"
              placeholder="Title"
              value={campaign.title}
              onChange={onInputChange}
            />
            <textarea
              type="text"
              id="description"
              name="description"
              placeholder="Description"
              value={campaign.description}
              onChange={onInputChange}
            />
            <input
              type="text"
              id="videoUrl"
              name="videoUrl"
              placeholder="video url"
              value={campaign.videoUrl}
              onChange={onInputChange}
            />
            <input
              type="text"
              id="imageUrl"
              name="imageUrl"
              placeholder="image url"
              value={campaign.imageUrl}
              onChange={onInputChange}
            />
          </Form>
          <InputDiv>
            <input type="button" value="Save campaign" onClick={btnSaveClick} />
          </InputDiv>
          <InputDiv>
            <BtnReturn>
              <Link href="/">Return</Link>
            </BtnReturn>
          </InputDiv>
        <MessageDiv>{message}</MessageDiv>
        </FormDiv>{" "}
      </Container>
    </>
  );
};
export default Campaign;
