"use client"; // Adicione isso no topo do arquivo

import { useState } from "react";
import React from "react";
import Link from "next/link";
import Footer from "@/components/Footer";
import { doLogin } from "@/services/Web3Service";
import Head from "next/head";

export default function Home() {
  const [wallet, setWallet] = useState("");
  const [error, setError] = useState("");

  function btnLoginClick() {
    doLogin()
      .then((wallet) => setWallet(wallet))
      .catch((error) => setError(error.message));
  }

  return (
    <div>
      <Head>
        <title>Donate Crypto | Index</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta charSet="utf-8" />
      </Head>
      <div className="container px-4 py-5">
        <div className="row flex-lg-row-reverse align-items-center py-5 g-5">
          {!wallet ? (
            <div className="col-10 col-sm-8 col-lg-6">
              <img
                src="https://media.dinheirama.com/medias/uploads/2017/03/17532473_ml.jpg"
                className="d-block mx-lg-auto img-fluid"
                alt="Crypto flowers"
                width="700"
                height="500"
                loading="lazy"
              />
            </div>
          ) : (
            <div className="col-10 col-sm-8 col-lg-6">
              <p className="mb-3">welcome {wallet}</p>
              <p className="mb-3">Votre portefeuille est connecté</p>
              <div>
                <p>
                  <Link href="/donate" className="btn btn-primary col-6 p-3">
                    Je veux faire un don
                  </Link>
                </p>
                <p>
                  <Link href="/create" className="btn btn-secondary col-6 p-3">
                    Je veux créer une campagne
                  </Link>
                </p>
              </div>
            </div>
          )}
          <div className="col-lg-6">
            <hi className="display-5 fw-bold text-body-lh-1 mb-3">
              Donate Crypto
            </hi>
            <p className="lead">
              Faites un don à une cause qui vous tient à cœur
            </p>
            <p className="lead mb-3">
              Choisissez parmi une liste de causes et faites un don en utilisant
              votre préférée crypto-monnaie.
            </p>
            {!wallet ? (
              <div className="d-grid gap-2 d-md-flex justify-content-md-start">
                <button
                  type="button"
                  className="btn btn-primary btn-lg px-4 me-md-2"
                  onClick={btnLoginClick}
                >
                  <img src="/images.png" width="64" className="me-3" />
                  conect wallet Metamask
                </button>
                {error}
              </div>
            ) : (
              <></>
            )}
          </div>
        </div>
        <Footer />
      </div>
    </div>
  );
}
