"use client";
import Head from "next/head";
import GlobalStyles from "../../GlobalStyles";
import SectionHome from "../../src/app/sectionHome/page";

export default function Home() {
  return (
    <>
      <GlobalStyles />
      <Head>
        <title>Donate Crypto</title>
        <meta charSet="UTF-8" />
        <meta name="description" content="Generated by Next.js" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <SectionHome />
    </>
  );
}
