version: '3.8'
services:
  db:
    image: postgres:15
    container_name: blockchaine_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 170465
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data

volumes:
  dbdata:
