import Head from "next/head";
import '../app/globals.css';
import Link from "next/link";
import Footer from "@/components/Footer";
import { useState } from "react";
import {addCampaign} from "@/services/Web3Service";

export default function Creatte() {

    const [campaign, setCampaign] = useState({});
    const [message, setMessage] = useState("");

    function onInputChange(e) {
        setCampaign(prevState => ({...prevState, [e.target.id]: e.target.value}));
    }

    function btnSaveClick() {
        setMessage("Sauver ... attendez ...");
        addCampaign(campaign)
        .then(tx =>setMessage(JSON.stringify(tx)))
        .catch(err => {
            console.error(err);
            setMessage(err.message);
        })
    }


  return (
    <>
      <Head>
        <title>Donate Crypto | Create</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta charSet="utf-8" />
      </Head>
      <div className="container">
        <hi className="display-5 fw-bold text-body-lh-1 mb-3">Create Crypto</hi>
        <p>
          Remplissez les champs pour inclure votre campagne sur la plate-forme
        </p>
        <hr className="mb-4" />
        <div className="col-6">
            <div className="form-floating mb-3">
                <input type="text" id="title" className="form-control" value={campaign.title} onChange={onInputChange} />
                <label htmlFor="title">Nom de la campagne:</label>
            </div>
            <div className="form-floating mb-3">
                <textarea id="description" className="form-control" value={campaign.description} onChange={onInputChange}/>
                <label htmlFor="description">description:</label>
            </div>
            <div className="form-floating mb-3">
                <input type="text" id="imageUrl" className="form-control" value={campaign.imageUrl} onChange={onInputChange}/>
                <label htmlFor="imageUrl">URL d'image:</label>
            </div>
            <div className="form-floating mb-3">
                <input type="text" id="videoUrl" className="form-control" value={campaign.videoUrl} onChange={onInputChange}/>
                <label htmlFor="videoUrl">URL vidéo:</label>
            </div>
        </div>
        <div className="col-6 mb-3">
            <input type="button" className="btn btn-primary col-12 p-3" value="Créer la campagne" onClick={btnSaveClick}/>
        </div>
        <div className="col-6 mb-3 ">
            <Link href="/" className="btn btn-secondary col-12 p-3">Return</Link>
        </div>
        {
          message
          ? <div className="alert alert-success p-3 col-6" role="alert">{message}</div>
          : <></>
        }
        <Footer />
      </div>
    </>
  );
}

